# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\regen\Documents\Files\Programming\C\Dragonrose

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\regen\Documents\Files\Programming\C\Dragonrose

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\regen\Documents\Files\Programming\C\Dragonrose\CMakeFiles C:\Users\regen\Documents\Files\Programming\C\Dragonrose\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\regen\Documents\Files\Programming\C\Dragonrose\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Dragonrose

# Build rule for target.
Dragonrose: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Dragonrose
.PHONY : Dragonrose

# fast build rule for target.
Dragonrose/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/build
.PHONY : Dragonrose/fast

Source/Engine/attack.obj: Source/Engine/attack.c.obj
.PHONY : Source/Engine/attack.obj

# target to build an object file
Source/Engine/attack.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/attack.c.obj
.PHONY : Source/Engine/attack.c.obj

Source/Engine/attack.i: Source/Engine/attack.c.i
.PHONY : Source/Engine/attack.i

# target to preprocess a source file
Source/Engine/attack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/attack.c.i
.PHONY : Source/Engine/attack.c.i

Source/Engine/attack.s: Source/Engine/attack.c.s
.PHONY : Source/Engine/attack.s

# target to generate assembly for a file
Source/Engine/attack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/attack.c.s
.PHONY : Source/Engine/attack.c.s

Source/Engine/bitboards.obj: Source/Engine/bitboards.c.obj
.PHONY : Source/Engine/bitboards.obj

# target to build an object file
Source/Engine/bitboards.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/bitboards.c.obj
.PHONY : Source/Engine/bitboards.c.obj

Source/Engine/bitboards.i: Source/Engine/bitboards.c.i
.PHONY : Source/Engine/bitboards.i

# target to preprocess a source file
Source/Engine/bitboards.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/bitboards.c.i
.PHONY : Source/Engine/bitboards.c.i

Source/Engine/bitboards.s: Source/Engine/bitboards.c.s
.PHONY : Source/Engine/bitboards.s

# target to generate assembly for a file
Source/Engine/bitboards.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/bitboards.c.s
.PHONY : Source/Engine/bitboards.c.s

Source/Engine/board.obj: Source/Engine/board.c.obj
.PHONY : Source/Engine/board.obj

# target to build an object file
Source/Engine/board.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/board.c.obj
.PHONY : Source/Engine/board.c.obj

Source/Engine/board.i: Source/Engine/board.c.i
.PHONY : Source/Engine/board.i

# target to preprocess a source file
Source/Engine/board.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/board.c.i
.PHONY : Source/Engine/board.c.i

Source/Engine/board.s: Source/Engine/board.c.s
.PHONY : Source/Engine/board.s

# target to generate assembly for a file
Source/Engine/board.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/board.c.s
.PHONY : Source/Engine/board.c.s

Source/Engine/data.obj: Source/Engine/data.c.obj
.PHONY : Source/Engine/data.obj

# target to build an object file
Source/Engine/data.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/data.c.obj
.PHONY : Source/Engine/data.c.obj

Source/Engine/data.i: Source/Engine/data.c.i
.PHONY : Source/Engine/data.i

# target to preprocess a source file
Source/Engine/data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/data.c.i
.PHONY : Source/Engine/data.c.i

Source/Engine/data.s: Source/Engine/data.c.s
.PHONY : Source/Engine/data.s

# target to generate assembly for a file
Source/Engine/data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/data.c.s
.PHONY : Source/Engine/data.c.s

Source/Engine/evaluate.obj: Source/Engine/evaluate.c.obj
.PHONY : Source/Engine/evaluate.obj

# target to build an object file
Source/Engine/evaluate.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/evaluate.c.obj
.PHONY : Source/Engine/evaluate.c.obj

Source/Engine/evaluate.i: Source/Engine/evaluate.c.i
.PHONY : Source/Engine/evaluate.i

# target to preprocess a source file
Source/Engine/evaluate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/evaluate.c.i
.PHONY : Source/Engine/evaluate.c.i

Source/Engine/evaluate.s: Source/Engine/evaluate.c.s
.PHONY : Source/Engine/evaluate.s

# target to generate assembly for a file
Source/Engine/evaluate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/evaluate.c.s
.PHONY : Source/Engine/evaluate.c.s

Source/Engine/hashkeys.obj: Source/Engine/hashkeys.c.obj
.PHONY : Source/Engine/hashkeys.obj

# target to build an object file
Source/Engine/hashkeys.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/hashkeys.c.obj
.PHONY : Source/Engine/hashkeys.c.obj

Source/Engine/hashkeys.i: Source/Engine/hashkeys.c.i
.PHONY : Source/Engine/hashkeys.i

# target to preprocess a source file
Source/Engine/hashkeys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/hashkeys.c.i
.PHONY : Source/Engine/hashkeys.c.i

Source/Engine/hashkeys.s: Source/Engine/hashkeys.c.s
.PHONY : Source/Engine/hashkeys.s

# target to generate assembly for a file
Source/Engine/hashkeys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/hashkeys.c.s
.PHONY : Source/Engine/hashkeys.c.s

Source/Engine/init.obj: Source/Engine/init.c.obj
.PHONY : Source/Engine/init.obj

# target to build an object file
Source/Engine/init.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/init.c.obj
.PHONY : Source/Engine/init.c.obj

Source/Engine/init.i: Source/Engine/init.c.i
.PHONY : Source/Engine/init.i

# target to preprocess a source file
Source/Engine/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/init.c.i
.PHONY : Source/Engine/init.c.i

Source/Engine/init.s: Source/Engine/init.c.s
.PHONY : Source/Engine/init.s

# target to generate assembly for a file
Source/Engine/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/init.c.s
.PHONY : Source/Engine/init.c.s

Source/Engine/io.obj: Source/Engine/io.c.obj
.PHONY : Source/Engine/io.obj

# target to build an object file
Source/Engine/io.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/io.c.obj
.PHONY : Source/Engine/io.c.obj

Source/Engine/io.i: Source/Engine/io.c.i
.PHONY : Source/Engine/io.i

# target to preprocess a source file
Source/Engine/io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/io.c.i
.PHONY : Source/Engine/io.c.i

Source/Engine/io.s: Source/Engine/io.c.s
.PHONY : Source/Engine/io.s

# target to generate assembly for a file
Source/Engine/io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/io.c.s
.PHONY : Source/Engine/io.c.s

Source/Engine/main.obj: Source/Engine/main.c.obj
.PHONY : Source/Engine/main.obj

# target to build an object file
Source/Engine/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/main.c.obj
.PHONY : Source/Engine/main.c.obj

Source/Engine/main.i: Source/Engine/main.c.i
.PHONY : Source/Engine/main.i

# target to preprocess a source file
Source/Engine/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/main.c.i
.PHONY : Source/Engine/main.c.i

Source/Engine/main.s: Source/Engine/main.c.s
.PHONY : Source/Engine/main.s

# target to generate assembly for a file
Source/Engine/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/main.c.s
.PHONY : Source/Engine/main.c.s

Source/Engine/makemove.obj: Source/Engine/makemove.c.obj
.PHONY : Source/Engine/makemove.obj

# target to build an object file
Source/Engine/makemove.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/makemove.c.obj
.PHONY : Source/Engine/makemove.c.obj

Source/Engine/makemove.i: Source/Engine/makemove.c.i
.PHONY : Source/Engine/makemove.i

# target to preprocess a source file
Source/Engine/makemove.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/makemove.c.i
.PHONY : Source/Engine/makemove.c.i

Source/Engine/makemove.s: Source/Engine/makemove.c.s
.PHONY : Source/Engine/makemove.s

# target to generate assembly for a file
Source/Engine/makemove.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/makemove.c.s
.PHONY : Source/Engine/makemove.c.s

Source/Engine/misc.obj: Source/Engine/misc.c.obj
.PHONY : Source/Engine/misc.obj

# target to build an object file
Source/Engine/misc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/misc.c.obj
.PHONY : Source/Engine/misc.c.obj

Source/Engine/misc.i: Source/Engine/misc.c.i
.PHONY : Source/Engine/misc.i

# target to preprocess a source file
Source/Engine/misc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/misc.c.i
.PHONY : Source/Engine/misc.c.i

Source/Engine/misc.s: Source/Engine/misc.c.s
.PHONY : Source/Engine/misc.s

# target to generate assembly for a file
Source/Engine/misc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/misc.c.s
.PHONY : Source/Engine/misc.c.s

Source/Engine/movegen.obj: Source/Engine/movegen.c.obj
.PHONY : Source/Engine/movegen.obj

# target to build an object file
Source/Engine/movegen.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/movegen.c.obj
.PHONY : Source/Engine/movegen.c.obj

Source/Engine/movegen.i: Source/Engine/movegen.c.i
.PHONY : Source/Engine/movegen.i

# target to preprocess a source file
Source/Engine/movegen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/movegen.c.i
.PHONY : Source/Engine/movegen.c.i

Source/Engine/movegen.s: Source/Engine/movegen.c.s
.PHONY : Source/Engine/movegen.s

# target to generate assembly for a file
Source/Engine/movegen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/movegen.c.s
.PHONY : Source/Engine/movegen.c.s

Source/Engine/perft.obj: Source/Engine/perft.c.obj
.PHONY : Source/Engine/perft.obj

# target to build an object file
Source/Engine/perft.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/perft.c.obj
.PHONY : Source/Engine/perft.c.obj

Source/Engine/perft.i: Source/Engine/perft.c.i
.PHONY : Source/Engine/perft.i

# target to preprocess a source file
Source/Engine/perft.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/perft.c.i
.PHONY : Source/Engine/perft.c.i

Source/Engine/perft.s: Source/Engine/perft.c.s
.PHONY : Source/Engine/perft.s

# target to generate assembly for a file
Source/Engine/perft.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/perft.c.s
.PHONY : Source/Engine/perft.c.s

Source/Engine/polybook.obj: Source/Engine/polybook.c.obj
.PHONY : Source/Engine/polybook.obj

# target to build an object file
Source/Engine/polybook.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/polybook.c.obj
.PHONY : Source/Engine/polybook.c.obj

Source/Engine/polybook.i: Source/Engine/polybook.c.i
.PHONY : Source/Engine/polybook.i

# target to preprocess a source file
Source/Engine/polybook.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/polybook.c.i
.PHONY : Source/Engine/polybook.c.i

Source/Engine/polybook.s: Source/Engine/polybook.c.s
.PHONY : Source/Engine/polybook.s

# target to generate assembly for a file
Source/Engine/polybook.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/polybook.c.s
.PHONY : Source/Engine/polybook.c.s

Source/Engine/polykeys.obj: Source/Engine/polykeys.c.obj
.PHONY : Source/Engine/polykeys.obj

# target to build an object file
Source/Engine/polykeys.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/polykeys.c.obj
.PHONY : Source/Engine/polykeys.c.obj

Source/Engine/polykeys.i: Source/Engine/polykeys.c.i
.PHONY : Source/Engine/polykeys.i

# target to preprocess a source file
Source/Engine/polykeys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/polykeys.c.i
.PHONY : Source/Engine/polykeys.c.i

Source/Engine/polykeys.s: Source/Engine/polykeys.c.s
.PHONY : Source/Engine/polykeys.s

# target to generate assembly for a file
Source/Engine/polykeys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/polykeys.c.s
.PHONY : Source/Engine/polykeys.c.s

Source/Engine/pvtable.obj: Source/Engine/pvtable.c.obj
.PHONY : Source/Engine/pvtable.obj

# target to build an object file
Source/Engine/pvtable.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/pvtable.c.obj
.PHONY : Source/Engine/pvtable.c.obj

Source/Engine/pvtable.i: Source/Engine/pvtable.c.i
.PHONY : Source/Engine/pvtable.i

# target to preprocess a source file
Source/Engine/pvtable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/pvtable.c.i
.PHONY : Source/Engine/pvtable.c.i

Source/Engine/pvtable.s: Source/Engine/pvtable.c.s
.PHONY : Source/Engine/pvtable.s

# target to generate assembly for a file
Source/Engine/pvtable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/pvtable.c.s
.PHONY : Source/Engine/pvtable.c.s

Source/Engine/search.obj: Source/Engine/search.c.obj
.PHONY : Source/Engine/search.obj

# target to build an object file
Source/Engine/search.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/search.c.obj
.PHONY : Source/Engine/search.c.obj

Source/Engine/search.i: Source/Engine/search.c.i
.PHONY : Source/Engine/search.i

# target to preprocess a source file
Source/Engine/search.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/search.c.i
.PHONY : Source/Engine/search.c.i

Source/Engine/search.s: Source/Engine/search.c.s
.PHONY : Source/Engine/search.s

# target to generate assembly for a file
Source/Engine/search.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/search.c.s
.PHONY : Source/Engine/search.c.s

Source/Engine/uci.obj: Source/Engine/uci.c.obj
.PHONY : Source/Engine/uci.obj

# target to build an object file
Source/Engine/uci.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/uci.c.obj
.PHONY : Source/Engine/uci.c.obj

Source/Engine/uci.i: Source/Engine/uci.c.i
.PHONY : Source/Engine/uci.i

# target to preprocess a source file
Source/Engine/uci.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/uci.c.i
.PHONY : Source/Engine/uci.c.i

Source/Engine/uci.s: Source/Engine/uci.c.s
.PHONY : Source/Engine/uci.s

# target to generate assembly for a file
Source/Engine/uci.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/uci.c.s
.PHONY : Source/Engine/uci.c.s

Source/Engine/validate.obj: Source/Engine/validate.c.obj
.PHONY : Source/Engine/validate.obj

# target to build an object file
Source/Engine/validate.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/validate.c.obj
.PHONY : Source/Engine/validate.c.obj

Source/Engine/validate.i: Source/Engine/validate.c.i
.PHONY : Source/Engine/validate.i

# target to preprocess a source file
Source/Engine/validate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/validate.c.i
.PHONY : Source/Engine/validate.c.i

Source/Engine/validate.s: Source/Engine/validate.c.s
.PHONY : Source/Engine/validate.s

# target to generate assembly for a file
Source/Engine/validate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/validate.c.s
.PHONY : Source/Engine/validate.c.s

Source/Engine/xboard.obj: Source/Engine/xboard.c.obj
.PHONY : Source/Engine/xboard.obj

# target to build an object file
Source/Engine/xboard.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/xboard.c.obj
.PHONY : Source/Engine/xboard.c.obj

Source/Engine/xboard.i: Source/Engine/xboard.c.i
.PHONY : Source/Engine/xboard.i

# target to preprocess a source file
Source/Engine/xboard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/xboard.c.i
.PHONY : Source/Engine/xboard.c.i

Source/Engine/xboard.s: Source/Engine/xboard.c.s
.PHONY : Source/Engine/xboard.s

# target to generate assembly for a file
Source/Engine/xboard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Dragonrose.dir\build.make CMakeFiles/Dragonrose.dir/Source/Engine/xboard.c.s
.PHONY : Source/Engine/xboard.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Dragonrose
	@echo ... Source/Engine/attack.obj
	@echo ... Source/Engine/attack.i
	@echo ... Source/Engine/attack.s
	@echo ... Source/Engine/bitboards.obj
	@echo ... Source/Engine/bitboards.i
	@echo ... Source/Engine/bitboards.s
	@echo ... Source/Engine/board.obj
	@echo ... Source/Engine/board.i
	@echo ... Source/Engine/board.s
	@echo ... Source/Engine/data.obj
	@echo ... Source/Engine/data.i
	@echo ... Source/Engine/data.s
	@echo ... Source/Engine/evaluate.obj
	@echo ... Source/Engine/evaluate.i
	@echo ... Source/Engine/evaluate.s
	@echo ... Source/Engine/hashkeys.obj
	@echo ... Source/Engine/hashkeys.i
	@echo ... Source/Engine/hashkeys.s
	@echo ... Source/Engine/init.obj
	@echo ... Source/Engine/init.i
	@echo ... Source/Engine/init.s
	@echo ... Source/Engine/io.obj
	@echo ... Source/Engine/io.i
	@echo ... Source/Engine/io.s
	@echo ... Source/Engine/main.obj
	@echo ... Source/Engine/main.i
	@echo ... Source/Engine/main.s
	@echo ... Source/Engine/makemove.obj
	@echo ... Source/Engine/makemove.i
	@echo ... Source/Engine/makemove.s
	@echo ... Source/Engine/misc.obj
	@echo ... Source/Engine/misc.i
	@echo ... Source/Engine/misc.s
	@echo ... Source/Engine/movegen.obj
	@echo ... Source/Engine/movegen.i
	@echo ... Source/Engine/movegen.s
	@echo ... Source/Engine/perft.obj
	@echo ... Source/Engine/perft.i
	@echo ... Source/Engine/perft.s
	@echo ... Source/Engine/polybook.obj
	@echo ... Source/Engine/polybook.i
	@echo ... Source/Engine/polybook.s
	@echo ... Source/Engine/polykeys.obj
	@echo ... Source/Engine/polykeys.i
	@echo ... Source/Engine/polykeys.s
	@echo ... Source/Engine/pvtable.obj
	@echo ... Source/Engine/pvtable.i
	@echo ... Source/Engine/pvtable.s
	@echo ... Source/Engine/search.obj
	@echo ... Source/Engine/search.i
	@echo ... Source/Engine/search.s
	@echo ... Source/Engine/uci.obj
	@echo ... Source/Engine/uci.i
	@echo ... Source/Engine/uci.s
	@echo ... Source/Engine/validate.obj
	@echo ... Source/Engine/validate.i
	@echo ... Source/Engine/validate.s
	@echo ... Source/Engine/xboard.obj
	@echo ... Source/Engine/xboard.i
	@echo ... Source/Engine/xboard.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

